In [8]:
# Вариант 27

#ЗАДАНИЕ 4.1.27
import numpy as np
import matplotlib.pyplot as plt

k=10 #необходимо выполнить 10 итераций
n=6 #порядок матрицы 

#функция для метода Зейделя (реализовано в приложении к заданию)
def zeid(B,c,n,k,x0): #x=Bx+c; x0-начальное приближение
    rez = np.zeros([k,n]) #нулевая матрица k*n
    y=np.array(x0)
    for m in range(k):
        x=np.array(y)
        for i in range(n):
            u=0
            j=0
            while (j>=0) and (j<=i):
                u+=B[i,j]*y[j]
                j+=1
            j=i+1
            while (j>=i) and (j<n):
                u+=B[i,j]*x[j]
                j+=1
            y[i]=u+c[i]
        for i in range(n):
            rez[m,i]=y[i]
    return rez

In [9]:
#данные 
A=np.array([[9.9,3.0,4.0,0,1.3,1.5],
            [1.98,9.8,0.8,5.94,0.42,-0.6],
            [3.96,-4.8,19.7,9.9,0.72,0.3],
            [1.98,1.2,1.1,6.93,0.81,-1.2],
            [9.9,-7.5,2.1,-9.9,29.5,0],
            [-2.97,-1.2,0.8,4.95,2.7,12.7]])

b = np.array([72.45,77.48,31.33,10.03,-78.74,64.22])

In [10]:
x=np.linalg.solve(A,b) #решение системы Ax=b, примем это решение за точное

In [11]:
#приведем систему к виду x=Bx+c
B = np.zeros([n,n])
c = np.zeros(n)

for i in range(A.shape[0]):
    c[i]=b[i]/A[i,i]
    for j in range(A.shape[1]):
        if i!=j:
            B[i,j]=-A[i,j]/A[i,i]
B

array([[ 0.        , -0.3030303 , -0.4040404 , -0.        , -0.13131313,
        -0.15151515],
       [-0.20204082,  0.        , -0.08163265, -0.60612245, -0.04285714,
         0.06122449],
       [-0.20101523,  0.24365482,  0.        , -0.50253807, -0.03654822,
        -0.01522843],
       [-0.28571429, -0.17316017, -0.15873016,  0.        , -0.11688312,
         0.17316017],
       [-0.33559322,  0.25423729, -0.07118644,  0.33559322,  0.        ,
        -0.        ],
       [ 0.23385827,  0.09448819, -0.06299213, -0.38976378, -0.21259843,
         0.        ]])

In [12]:
np.linalg.norm(B,np.inf) #Достаточное условие сходимости выполняется, так как норма меньше 1

0.9989847715736041

In [13]:
x1=[0.0,0.0,0.0,0.0,0.0,0.0] #первое начальное приближение 
z1=zeid(B,c,n,k,x1)
z1 #10 итераций по методу Зейделя с первым начальным приближением 

array([[ 7.31818182,  6.42755102,  1.68539314, -2.02409721, -4.29021205,
         8.9702835 ],
       [ 3.89369947,  8.94177114,  4.02375033,  0.20254492, -1.92098381,
         6.88814736],
       [ 2.1913882 ,  7.51618734,  2.84473459,  0.48545342, -1.53326413,
         6.23691959],
       [ 3.14751148,  7.19129275,  2.42695153,  0.17676432, -2.01058642,
         6.67792906],
       [ 3.41062468,  7.40679853,  2.59242822,  0.17016215, -2.05809116,
         6.762072  ],
       [ 3.2719497 ,  7.43249748,  2.63033837,  0.21943877, -1.99118094,
         6.69625067],
       [ 3.25003165,  7.397066  ,  2.59990471,  0.21744882, -1.99133474,
         6.69050249],
       [ 3.27395602,  7.39557749,  2.59582604,  0.21054106, -2.00176989,
         6.70112456],
       [ 3.2758159 ,  7.40081917,  2.60042038,  0.21143177, -2.00108955,
         6.70127358],
       [ 3.2722593 ,  7.40060279,  2.60060784,  0.21240194, -1.99963876,
         6.69972301]])

In [14]:
max(abs(z1[k-1]-x))#абсолютная погрешность в первом случае

0.000607838727186838

In [15]:
x2=[3.2,7.4,2.6,0,-2,6.7]#второе начальное приближение - ближе к решению
z2=zeid(B,c,n,k,x2)
z2#10 итераций по методу Зейделя с вторым начальным приближением 

array([[ 3.27272727,  7.52857143,  2.73792603,  0.16796474, -1.99194942,
         6.71895928],
       [ 3.17410878,  7.43624567,  2.65026261,  0.22838544, -1.95580915,
         6.66146178],
       [ 3.2414719 ,  7.3881003 ,  2.59418177,  0.21219695, -1.99209666,
         6.69022304],
       [ 3.27912759,  7.39819862,  2.5980965 ,  0.20828987, -2.00375615,
         6.70373833],
       [ 3.27396906,  7.40261661,  2.60239368,  0.21201974, -1.99995595,
         6.70041704],
       [ 3.27089824,  7.40025929,  2.60047387,  0.21259074, -1.99919643,
         6.69921307],
       [ 3.27247095,  7.39964589,  2.5997119 ,  0.21207131, -2.00000025,
         6.69994425],
       [ 3.27295946,  7.40000345,  2.59998011,  0.21204781, -2.00010026,
         6.7001058 ],
       [ 3.2727314 ,  7.40005606,  2.60005177,  0.21213215, -1.99998715,
         6.69999601],
       [ 3.27268829,  7.39999623,  2.60000101,  0.21213065, -1.99998478,
         6.69998355]])

In [16]:
max(abs(z2[k-1]-x))#абсолютная погрешность во втором случае

3.898681599778797e-05

In [17]:
#погрешности существенно различаются - чем ближе начальное решение к корню, тем погрешность меньше